{-# OPTIONS_GHC -Wno-unused-imports #-}

-- |
-- [Previous Chapter: (Docs) Components]("Mischief.ECS.Tutorial.Documentation.Components")
--
-- [Next Chapter: (Docs) Systems]("Mischief.ECS.Tutorial.Documentation.Systems")
--
-- [Main Page]("Mischief.ECS")
module Mischief.ECS.Tutorial.Documentation.Queries
  ( -- * Learn You an ECS for Great Mischief! - 3.3. (Docs) Queries

    -- * Query Data
    -- $qd

    -- * Query Filters
    -- $qf

    -- * Query
    -- $query

    -- * [Next Chapter: (Docs) Systems]("Mischief.ECS.Tutorial.Documentation.Systems")
  )
where

import Mischief.ECS

-- Each query associates an output type to the types you put into it.
--
-- For instance,
--
-- @
-- x <- 'query' ('C' \@A, 'M' \@B)
-- @
--
-- Will have an output type of:
--
-- @
-- ('Result' A, 'Maybe' ('Result' B))
-- @
--
-- With an actual return type of:
--
-- @
-- x :: ['Result' A, 'Maybe' ('Result' B)]
-- @
--
-- Because @query@ actually returns @[Output]@.
--
-- @single@ on the other hand, returns a @Maybe Output@, only outputting something if there is exactly one entity which matches the query.
--
-- @
-- x <- 'single' ('C' \@A, 'M' \@B)
-- @
--
-- @
-- x :: 'Maybe' ('Result' A, 'Maybe' ('Result' B))
-- @
--
-- @get@ queries the components of a specific entity:
--
-- @
-- x <- 'get' ('C' \@A) e
-- @
--
-- @
-- x :: 'Maybe' ('Result' A)
-- @
--
-- @get@ returns @'Nothing'@ if the entity doesn't exist or if it doesn't contain any of the components.

-- $val
-- Working with @Result c@ can be annoying, especially if you only want to read the value of a component and not mutate anything.
--
-- That's why all query types can be wrapped in a @Val@ in order to extract their values out of the @Result@:
--
-- @
-- 'query' ('C' \@Foo, 'Val' ('C' \@Bar, 'M' \@Baz))
-- @
--
-- Will return:
--
-- @
-- ['Result' Foo, (Bar, 'Maybe' Baz)]
-- @
--
-- @Val@ maps anything that looks like a @Result c@ to just @c@, while leaving most other things be as they are.

-- $qd
-- Component @c@ query:
--
-- @
-- ['qd'|c|]
-- @
--
-- @
-- ('C' \@c)
-- @
--
-- Outputs @c@.
--
-- Optional component @c@ query:
--
-- @
-- ['qd'|Maybe c|]
-- @
--
-- @
-- ('M' \@c)
-- @
--
-- Outputs @'Maybe' c@.
--
-- Bool component @c@ query:
--
-- @
-- ['qd'|Has c|]
-- @
--
-- @
-- ('Has' \@c)
-- @
--
-- Outputs @'Bool'@.
--
-- Relationship @(c, e)@ query:
--
-- @
-- ['qd'|c -> e|]
-- @
--
-- @
-- ('R' \@c e)
-- @
--
-- Outputs @'Rel' c@.
--
-- Relationship @(c, *)@ query:
--
-- @
-- ['qd'|c -> *|]
-- @
--
-- @
-- ('R' \@c 'Any')
-- @
--
-- Outputs @['Rel' c]@ or @'Rel' c@ (depending on exclusivity).
--
-- Transitive @(c, q)@ query:
--
-- @
-- ['qd'|c -> (q)|]
-- @
--
-- @
-- ('R' \@c ('Q' q))
-- @
--
-- Outputs @['From' out]@ or @'From' out@ (depending on exclusivity).
-- Where @out@ is the output of @q@.
--
-- If @R \@c t@ is valid query data, @MR \@c t@ and @HasR \@c t@ are also valid query data,
-- outputting the result wrapped in @Maybe@, or replacing it with a @Bool@.

-- $qf
-- @t@ can be: @C \@c@, @R \@c e@ or @R \@c Any@.
--
-- @With t@ - entity must have @t@. Can be Archetype Filter.
--
-- @
-- ['qf'|With t|]
-- @
--
-- @
-- ('With' t)
-- @
--
-- @Without t@ - entity must not have @t@. Can be Archetype Filter.
--
-- @
-- ['qf'|Without t|]
-- @
--
-- @
-- ('Without' t)
-- @
--
-- @Added t@ - entity must have had @t@ added since this system last ran.
--
-- @
-- ['qf'|Added t|]
-- @
--
-- @
-- ('Added' t)
-- @
--
-- @Changed t@ - entity must have had @t@ inserted since this system last ran.
--
-- @
-- ['qf'|Changed t|]
-- @
--
-- @
-- ('Changed' t)
-- @
--
-- @a && b@ - both filters must be true.
--
-- @
-- ['qf'|a, b|] | ['qf'|a && b|]
-- @
--
-- @
-- (a '`And`' b)
-- @
--
-- @a || b@ - one of the filters must be true.
--
-- @
-- ['qf'|a || b|]
-- @
--
-- @
-- (a '`Or`' b)
-- @
--
-- @!a@ - @a@ must be false.
--
-- @
-- ['qf'|!a|]
-- @
--
-- @
-- ('`Not`' a)
-- @

-- $query
-- TODO
