{-# OPTIONS_GHC -Wno-unused-imports #-}

-- |
-- Module: Systems Tutorial
-- Description: Tutorial on using @Systems@
--
-- This module contains a more in-depth tutorial on using @Mischief Systems@.
--
-- [Previous Chapter: Components]("MischiefECS.Tutorial.Components")
--
-- [Main Page]("MischiefECS")
module MischiefECS.Tutorial.Systems
  ( -- * Learn You an ECS for Great Mischief! - 3. Systems

    -- * Introduction
    -- $intro

    -- * Scheduling
    -- $scheduling

    -- * Deferring
    -- $deferring

    -- * ParSystem
    -- $par

    -- * Parallelism
    -- $parallelism

    -- * Simulating Asynchronicity with runAfter
    -- $async
  )
where

import Control.Concurrent (threadDelay)
import Control.Monad.Reader
import Data.Foldable (for_)
import MischiefECS

-- $intro
-- A 'System' in Mischief is simply a 'Monad' allowing operations to be executed on a 'World'.
-- Being a wrapper around @'ReaderT' 'World' 'IO'@, it also enabled 'IO' access through 'liftIO'.
--
-- Here is a simple system that spawns an entity and prints its @'Entity'@:
--
-- @
-- foo :: 'System' ()
-- foo = do
--   e <- 'spawn' ()
--   'liftIO' $ 'print' e
-- @
--
-- Note that, unlike other ECS's, systems here are fully @composable@. Even the 'spawn' used above is a 'System' that we are calling from another 'System'!
--
-- In the functions provided by @Mischief@ you may see the 'MonadSystem' typeclass being used:
--
-- @
-- 'query' :: forall qd m w. ('Queryable' qd, 'MonadSystem' w m) => m ['QueryOutput' qd]
-- @
--
-- This makes the function accept other types of systems, besides just the normal 'System', such as 'ParSystem', but more on that later.

-- $scheduling
-- Scheduling a system means adding it to a @'Schedule'@. Mischief has a few predefined schedules:
--
-- @The startup schedules@ run once at the start of the app, before any Update, in this order:
-- * 'PreStartup'
-- * 'Startup'
-- * 'PostStartup
--
-- @The update shchedules@ run once every frame, in this order:
--
-- *'First'
-- *'PreUpdate'
-- *'Update'
-- *'PostUpdate'
-- 'Last'
--
-- Note that @First@ and @Last@ are reserved mostly for ECS internal logic and should generally be avoided.
--
-- In order to add a system @s :: 'System' ()@ to a schedule @sc@, you can use this 'Plugin':
--
-- @
-- 'addSystems' :: ('Schedule' sc, 'SystemConfig' s) => sc -> s -> 'Plugin' ()
-- @
--
-- @'SystemConfig'@ is a typeclass that allows you to provide stuff like a @'System' ()@, a tuple of systems, or a system ordered to happen after / before another system.
--
-- @
-- 'addSystems' 'Update' a
-- @
--
-- @
-- 'addSystems' 'Update' (a, b)
-- @
--
-- @
-- 'addSystems' 'Update' $ a '`after`' b
-- @
--
-- @
-- 'addSystems' 'Update' $ (a, b) '`after`' c '`before`' d
-- @
--
-- Keep in mind that when you add @a '`after`' b@, this will just add @a@ to the schedule; @b@ needs to be added separately, and doesn't need
-- to be in the same plugin. It's even possible to create and order a system to run before a system defined internally by Mischief, as long as
-- that system is exported and visible to you.
--
-- Additionally, these are equivalent:
--
-- @
-- 'addSystems' b
-- 'addSystems' 'Update' $ a `'after'` b
-- @
--
-- @
-- 'addSystems' 'Update' $ a `'after'` b
-- 'addSystems' b
-- @
--
-- Note that when you order systems, they will be ordered only in the context of the current schedule.
-- So @'addSystems' 'Update' $ a '`after`' b@ will order @a@ after the system @b@ that's in Update, if there is one at the point of running the app.
--
-- Also, a system can be added to any number of schedules. Adding a system twice to the same schedule will have no effect.

-- $deferring
-- Time to learn a very powerful and important system:
--
-- @
-- 'defer' :: 'System' a -> 'System' ()
-- @
--
-- All the systems presented so far in this tutorials had their effect applied immediately. When you write @'set' 'Name' $ 'Name' \"Player\"@,
-- you are /immediately/ mutating the respective component. When you do @e <- 'spawn' ()@, you are /immediately/ spawning that entity into the World.
--
-- @'defer'@ takes a system and adds it to an internal list instead of applying it.
--
-- @
-- 'defer' $ 'spawn' ()
-- @
--
-- @
-- 'defer' $ do
--   e <- 'spawn' ()
--   'insert' ('Name' \"Name\") e
-- @
--
-- You can then use @'flush' :: 'System' ()@ to empty the list of deferred systems, applying all of them.
--
-- Mischief automatically runs @'flush'@ at each @sync point@, usually after running each system.
--
-- There is also a special @'deferSpawn'@ primitive that immediately return an @'Entity'@ you can use but defers the actual spawn.

-- $par
-- So why is @'defer'@ so important? The answer is: @'ParSystem'@.
--
-- @'ParSystem'@ is a special variant of @'System'@ that, statically, forbids any mutations to the 'World'.
--
-- Most systems, such as 'set', 'spawn', and so on, are only defined for 'System'. And 'ParSystem' is designed in such a way
-- that you can't externally access the 'World' from within it, preventing you from writing your own. Basically, a @'ParSystem'@ lets
-- you /read/ data via queries, while restricting the systems that cause mutations.
--
-- However, certain systems are defined with a generic 'MonadSystem':
--
-- @
-- 'query' :: forall qd m w. ('Queryable' qd, 'MonadSystem' w m) => m ['QueryOutput' qd]
-- @
--
-- 'MonadSystem' is a typeclass instanced by both 'System' and 'ParSystem', meaning 'query' can work in both.
--
-- So, how do you actually write logic in a @'ParSystem'@ that has effects on the 'World'? You guessed it!
--
-- @'defer'@ also works for both!
--
-- Here's a 'ParSystem' that iterates over all entities with a specific name and renames them.
--
-- @
-- changeName :: 'Name' -> 'Name' -> 'ParSystem' ()
-- changeName oldName newName = do
--   names <- 'query'' \@'Name' $ 'check' (== oldName)
--   'for_' names $ \name -> do
--     'defer' $ 'set' name newName
-- @
--
-- The @'set'@ will just be deferred and applied at the next sync point.

-- $parallelism
-- Now that we've learned about 'ParSystem' and its constraints, let's look into how we actually parallelize systems.
--
-- The simplest way is to use the following function:
--
-- @
-- 'par' :: ['ParSystem' ()] -> 'System' ()
-- @
--
-- You provide a list of ParSystems, and Mischief will run them in parallel for you.
--
-- @
-- s :: 'System' ()
-- s = do
--   par [p1, p2]
--
-- p1 :: 'ParSystem' ()
-- p1 = ...
--
-- p2 :: 'ParSystem' ()
-- p2 = ...
-- @
--
-- Another way is to use @'parIter'@, a function that works similarly to 'for_':
--
-- @
-- players <- query @Entity $ 'with' @Player
-- 'parIter' players $ \entity -> do
--   ...
-- @

-- $async
-- Mischief doesn't currently natively suppot asynchornous systems, however, the same effect can be achieved with this primitive:
--
-- @
-- 'runAfter' :: ('MonadSystem' w m) => 'IO' a -> (a -> 'System' ()) -> m ()
-- @
--
-- You provide it an 'IO' action that returns an @a@, and a system which takes that @a@.
--
-- This will run the 'IO' fully asychrnously and then will add the system to a special async-friendly deferred list that
-- will be applied at the first sync point possible.
--
-- We can look at @'delay'@ as an example of how this may be useful:
--
-- @
-- 'delay' :: ('MonadSystem' w m) => 'Int' -> 'System' () -> m ()
-- 'delay' d system = 'runAfter' ('threadDelay' d) ('const' system)
-- @
--
-- It allows delaying any system by an amount of time:
--
-- @
-- 'delay' 500 $ 'insert' (Health 100) player
-- @
