{-# OPTIONS_GHC -Wno-unused-imports #-}

-- |
-- Module: Components Tutorial
-- Description: Tutorial on using @Components@
--
-- This module contains a more in-depth tutorial on @Mischief Components@.
--
-- [Previous Chapter: App and Plugins]("Mischief.ECS.Tutorial.App")
--
-- [Main Page]("Mischief.ECS")
module Mischief.ECS.Tutorial.Components
  ( -- * Learn You an ECS for Great Mischief! - 2. Components

    -- * Introduction
    -- $introduction

    -- * The Name Component
    -- $name

    -- * Operations
    -- $ops

    -- * Query Results
    -- $results

    -- * Meta Components
    -- $meta

    -- * Required Components
    -- $required

    -- * Relationships
    -- $relationships

    -- * [Next Chapter: Systems]("Mischief.ECS.Tutorial.Systems")
  )
where

import Data.Default (Default (def))
import Data.Foldable
import GHC.Generics (Generic)
import GHC.Records (HasField)
import Mischief.ECS

-- $introduction
-- A component is any type which derives the 'Component' typeclass. They can be both carriers of data or marker components used for querying (@Tags@ from @Flecs@):
--
-- Component that carries data.
--
-- @
-- data Health = Health 'Int' deriving ('Component')
-- @
--
-- Marker components.
--
-- @
-- data Player = Player deriving ('Component')
-- data Enemy = Enemy deriving ('Component')
-- @

-- $name
-- @'Name'@ is a special component provided by Mischief that is internally added to every spawned entity, based on its @Entity@ index,
-- if none is provided on spawn. It can be, of course, changed at any time.
--
-- Consider this system that prints the name of a given Entity:
--
-- @
-- printName :: 'Entity' -> 'System' ()
-- printName e = 'info' . 'text' '=<<' 'get' ('C' \@'Name') e
-- @
--
-- Notice how the Names behave here:
--
-- @
-- foo <- 'spawn' ()
-- printName foo
--
-- insert ('Name' \"Foo\") foo
-- printName foo
--
-- bar <- 'spawn' ('Name' \"Bar\")
-- printName bar
-- @
--
-- @
-- >> [INFO] Just \"Entity 15v1\"
-- >> [INFO] Just \"Foo\"
-- >> [INFO] Just \"Bar\"
-- @
--
-- === __Don't know what =<< is?__
--
-- @=<<@ is just an operator which takes the result of a monadic action on the right, and applies it
-- to the monadic action on the left. It's equivalent to writing:
--
-- @
-- printName e = do
--   x <- 'get' ('C' \@'Name') e
--   'info' $ 'text' x
-- @
--
-- There is also the @>>=@ operator whcih does the same but in the opposite direction.
--
-- @
-- printName e = 'get' ('C' \@'Name') e '>>=' 'info' . 'text'
-- @

-- $ops
-- As you must have seen many times already, we can use @spawn@ to create a new entity, @insert@ to add or change one of its components,
-- @remove@ to remove them, and @despawn@ to erase the entity.
--
-- @
-- data CompA = CompA 'Int' 'Int' deriving ('Component', 'Show')
--
-- data CompB = CompB 'String' deriving ('Component', 'Show')
--
-- data CompC = CompC deriving ('Component', 'Show')
--
-- main :: 'IO' ()
-- main = do
--   app <- 'newApp' MainPlugin
--   'runApp' app
--
-- data MainPlugin = MainPlugin deriving ('Eq')
--
-- instance 'Plugin' MainPlugin where
--   'Mischief.ECS.App.Plugins.init' _ = do
--     foo <- 'spawn' (Name \"Foo\", CompA 10 10, CompB \"Component B on Foo\", CompC)
--     bar <- 'spawn' (Name \"Bar\", CompA 15 3,  CompB \"Component B on Bar\")
--     baz <- 'spawn' (Name \"Baz\", CompA 0 0,   CompB \"Component B on Baz\", CompC)
--
--     'info' . 'text' '=<<' 'query' ('C' \@Name, 'C' \@CompA, 'M' \@CompB, 'M' \@CompC)
--
--     'insert' (Name \"Foo2\", CompA 100 100, CompC) foo
--     'remove' ('C' \@CompC, 'C' \@CompB) baz
--     'insert' (CompA 150 5) bar
--
--     'info' . 'text' '=<<' 'query' ('C' \@Name, 'C' \@CompA, 'M' \@CompB, 'M' \@CompC)
-- @
--
-- @
-- >> [Info] [
--   (\"Foo\", CompA 10 10, Just CompB \"Component B on Foo\", Just CompC),
--   (\"Baz\", CompA 0 0,   Just CompB \"Component B on Baz\", Just CompC),
--   (\"Bar\", CompA 15 3,  Just CompB \"Component B on Bar\", Nothing)
-- ]
--
-- >> [Info] [
--   ("\Foo2\", CompA 100 100, Just CompB \"Component B on Foo\", Just CompC),
--   (\"Bar\",  CompA 150 5,   Just CompB \"Component B on Bar\", Nothing   ),
--   (\"Baz\",  CompA 0 0,     Nothing, Nothing)
-- ]
-- @

--
-- @
-- data CompA = CompA Int Int deriving (String)
-- @
--
--
-- @
--
-- @

-- $results
-- A @'Result' c@ is a wrapper around the component @c@ that's produced by a query.
--
-- @
-- newtype 'Result' c = 'Result' (c, 'Entity')
-- @
--
-- @
-- 'value' :: 'Result' c -> c
-- 'entityOf' :: 'Result' c -> Entity
-- @
--
-- The inner component's value can be obtained via the @value@ function.
--
-- @
-- 'Just' name <- 'get' \@'Name' e
-- let name' = 'value' name
-- @
--
-- @
-- name  :: 'Result' 'Name'
-- name' :: 'Name'
-- @
--
-- If the component has record fields, every field will be inherited by the 'Result' (via a 'HasField' instance)
--
-- @
-- data Pos = Pos {x :: 'Float', y :: 'Float'}
-- @
--
-- @
-- 'Just' pos <- 'get' @Pos e
-- let x = pos.x
-- let y = pos.y
-- @
--
-- @
-- pos :: 'Result' Pos
-- x   :: 'Float'
-- y   :: 'Float'
-- @
--
-- Some typeclasses, namely 'Show', 'Eq', 'Ord' are also implemented for a @'Result' c@ if they are for the underlying @c@.
--
-- Note that the value of a 'Result' is the value gotten at the time of querying. It could be outdated, in case the live value
-- was changed after querying.
--
-- A 'Result' can be used in various functions such as:
--
-- * Set a new value for this component.
--
-- @
-- 'set' :: 'Result' c -> c -> 'System' ()
-- @
--
-- * Change the value of a component only if the value is different from the current one.
-- Useful if you don't wish to trigger change detection.
--
-- @
-- 'setIfNeq' :: ('Eq' c) => 'Result' c -> c -> 'System' ()
-- @
--
-- * Modify the value of this component (the function will be applied over the live value).
--
-- @
-- 'modify' :: 'Result' c -> (c -> c) -> 'System' ()
-- @
--
-- * Get the live value from the 'World'.
--
-- @
-- 'update' :: 'Result' c -> 'System' ('Maybe' ('Result' c))
-- @
--
-- * Remove the component from the entity.
--
-- @
-- 'delete' :: 'Result' c -> 'System' ()
-- @

-- $meta
-- Each component has a corresponding entity in the 'World', called a @Meta Component@.
--
-- The components on that entity store information about the component itself. Such as which archetypes it is part of.
--
-- A component's entity can be accessed by using @'meta' :: forall c. ('Component' c) => 'System' 'Entity'@.
-- For instance, the entity of 'Name' is @'meta' \@'Name'@.
--
--  This is, in fact, how @resources@ are stored: by inserting the value of a component unto its own corresponding entity.
--
-- @
-- 'res' :: forall c. ('Queryable' c, 'Component' c) => 'System' ('Maybe' ('Result' c))
-- 'res' = do
--   meta <- 'meta' \@c
--   'get' \@c meta
-- @
--
-- @
-- 'insertRes' :: forall r. ('Component' r, 'Bundle' r) => r -> 'System' ()
-- 'insertRes' res = do
--   entity <- 'meta' \@r
--   'insert' res entity
-- @
--
-- Most users should avoid tinkering with @Meta Components@ unless they have a good reason to,
-- and should absolutely never remove or change any components added to them by the @ECS@.

-- $required
-- Each component can have a list of components that it @requires@.
--
-- If two components, @B@ and @C@ are required by component @A@, they will be added to each entity that @A@ is added to.
--
-- @Requirements@ can be set via a custom instance of 'Component'.
--
-- @
-- data B = B deriving ('Generic', 'Component', 'Default')
-- data C = C deriving ('Generic', 'Component', 'Default')
--
-- data A = A
-- instance 'Component' A where
--   'required' = 'require' \@(B, C)
-- @
--
-- As implied above, in order for a component to be required by another, it needs to implement 'Default'.
-- That can either be a 'Generic' derive, or a fully custom instance:
--
-- @
-- data Health = Health 'Int'
-- instance 'Default' Health where
--   'def' = Health 0
-- @

-- $relationships
-- Mischief implement @Relationships@ in a similar way to @Flecs@.
--
-- A component is actually indexed by 'ComponentId', which is:
--
-- @
-- data 'ComponentId' = 'ComponentId' {id :: 'Entity', entity :: 'Maybe' 'Entity'}
-- @
--
-- The first field, @id@, is the entity corresponding to the component, while the second field, @entity@, is an optional reference to another entity.
--
-- This means that each 'ComponentId' can either be a simple component, or a pair between a component and an entity (technically even between
-- two components or two entities but that's not directly allowed by the API).
--
-- Let's consider the following component:
--
-- @
-- data Likes = Likes deriving ('Component')
-- @
--
-- And three spawned entities: @alice@, @bob@, @charlie@.
--
-- We can insert relationships between entities using the special 'Rel' type.
--
-- @
-- 'insert' ('Rel' (Likes, alice), 'Rel' ('Likes' charlie)) bob
-- 'insert' ('Rel' (Likes bob)) alice
-- @
--
-- The 'WithR' query filter lets us easily query for components of entities that have a certain relationship with a certain entity.
--
-- Getting a list of all entities that like bob.
--
-- @
-- x <- 'query'' ('C' @'Entity') ('WithR' @Likes bob)
-- @
--
-- Getting a list of all entities that like anyone.
--
-- @
-- x <- 'query'' ('C' @'Entity') ('WithR' @Likes Any)
-- @
--
-- We can also modify @Likes@ to have an @Int@ as well, representing how much an entity likes another:
--
-- @
-- data Likes = Likes 'Int' deriving ('Component')
-- @
--
-- @
-- 'insert' ('Rel' (Likes 5, alice), 'Rel' (Likes 8, charlie)) bob
-- @
--
-- The 'R' marker type can be used in a query to get a @['Result' ('Rel' c)]@ for each entity.
--
-- Getting the name and all the Likes relationships of all entities.
--
-- @
-- x <- query (C \@Name, 'R' \@Likes Any)
-- @
--
-- @
-- x :: [('Result' Name, ['Result' ('Rel' Likes)])]
-- @
--
--
-- Getting the name and the Like relationship with bob for all entities.
--
-- @
-- x <- query (C \@Name, 'R' \@Likes bob)
-- @
--
-- @
-- x :: [('Result' Name, 'Result' ('Rel' Likes))]
-- @
--
-- Note that @'R' \@Likes@ will limit the query to only the archetypes that contain any relation with @Likes@.
-- You can also use @'MR'@ (Maybe relationship) to also include the entities that don't contain such relationships.
--
-- A component can be made @exclusive@ by setting the following 'Bool' in the 'Component' instance:
--
-- @
-- instance 'Component' Likes where
--   'isExclusiveRel' = 'True'
-- @
--
-- If a component is exclusive, there can only be one relationship containing it on an entity at once.
--
-- For instance, if we do:
--
-- @
-- 'insert' ('Rel' (Likes, alice) bob
-- 'insert' ('Rel' (Likes, charlie)) bob
-- @
--
-- @(Likes, charlie)@ will overwrite @(Likes, alice)@.
--
-- This is useful for relationships such as 'ChildOf', since an entity can only have one parent at a time.

-- $next
-- "Mischief.ECS.Tutorial.Systems"