{-# OPTIONS_GHC -Wno-unused-imports #-}

-- |
-- Module: Relationships Tutorial
-- Description: Tutorial on using @Relationships@
--
-- This module contains a more in-depth tutorial on @Mischief Relationships@.
--
-- [Previous Chapter: Components]("Mischief.ECS.Tutorial.Components")
--
-- [Next Chapter: Queries]("Mischief.ECS.Tutorial.Queries")
--
-- [Main Page]("Mischief.ECS")
module Mischief.ECS.Tutorial.Relationships
  ( -- * Learn You an ECS for Great Mischief! - 3. Relationships

    -- * Introduction
    -- $intro

    -- * Insertion
    -- $insertion

    -- * Removal
    -- $removal

    -- * Querying
    -- $query

    -- * Hooks
    -- $hooks

    -- * [Next Chapter: Queries]("Mischief.ECS.Tutorial.Queries")
  )
where

import Mischief.ECS

-- $intro
-- Mischief implement @Relationships@ in a similar way to @Flecs@.
--
-- When a component is added to an entity, it is actually indexed by a @ComponentId@:
--
-- @
-- data 'ComponentId' = ComponentId {id :: 'Entity', entity :: 'Maybe' 'Entity'}
-- @
--
-- The first field, @id@, is the entity corresponding to the component, while the second field, @entity@, is an optional reference to another entity.
--
-- This means that each @ComponentId@ can either be a simple component, or a pair between a component and an entity (technically even between
-- two components or two entities but that's not directly allowed by the API).
--
-- So a relationship in Mischief is a pair between a component and an entity. It can be inserted on entities using @Rel@:
--
-- @
-- data 'Rel' c = Rel {comp :: c, target :: 'Entity'}
-- @
--
-- For instance, this is how we spawn an entity @b@ that's a child of @a@:
--
-- @
-- a <- 'spawn' ()
-- b <- 'spawn' ('Rel' 'ChildOf' a)
-- @

-- $insertion
-- Let's consider the following component, which will symbolize that an entity likes another, and by how much:
--
-- @
-- data Likes = Likes 'Int' deriving ('Component')
-- @
--
-- And three spawned entities: @alice@, @bob@, @charlie@.
--
-- As mentioned before, we can insert a relationship using the 'Rel' type.
--
-- @
-- 'insert' ('Rel' (Likes 3) alice, 'Rel' (Likes 5) charlie) bob
-- 'insert' ('Rel' (Likes 2) bob) alice
-- @
--
-- If we insert a second relationship with the same component and the same target, its value will overwrite the other. For instance, the following code
-- will make @alice@ like @bob@ by 3 instead of 2:
--
-- @
-- 'insert' ('Rel' (Likes 3) bob) alice
-- @

-- $removal
-- Removing relationships can be done through the @remove@ function, same as normal components. But instead of using the @'C'@ marker, we will use the @'R'@ marker.
--
-- Making @bob@ stop liking @alice@.
--
-- @
-- 'remove' ('R' \@Likes alice) bob
-- @
--
-- The @'R'@ marker takes a type hint of the relationship's type (@\@Likes@), and a target Entity (@alice@). But it can also be given the @Any@ wildcard instead:
--
-- @
-- 'remove' ('R' \@Likes 'Any') bob
-- @
--
-- This will remove all @Likes@ relationships from @bob@, making him not like anyone.

-- $query
-- Relationships can be queried using the @R@ marker.
--
-- @
-- x <- 'query' ('R' \@Likes alice)
-- @
--
-- @
-- x :: ['Result' ('Rel' Likes)]
-- @
--
-- @Result (Rel c)@ is the return type of @R \@c e@. It can be used in most Result-based operation discussed in the previous chapter, such as @'set'@ and @'delete'@.
--
-- Querying can also be done using the @Any@ wildcard:
--
-- @
-- x <- 'query' ('R' \@Likes Any)
-- @
--
-- @
-- x :: [['Result' ('Rel' Likes)]]
-- @
--
-- As you can see, the return type of @'R' \@c Any@ is @[Result (Rel c)]@. It's returning a list of relationships, rather than a single relationship.
--
-- Remember that the fields of the inner type of a Result are inherited by the Result itself. So we can just use @.comp@ and @.target@ to get the component and target of a @Result (Rel c)@.
--
-- @
-- 'Just' x <- 'get' ('R' \@Likes alice) bob
-- @
--
-- @
-- x.target :: Entity
-- x.comp   :: Likes
-- @
--
-- In the case of querying for @R c Any@, the query will only match entities that have at least one such relationship. The resulting @[Result (Rel c)]@ should never be empty.
--
-- If you wish to also include entities that do not have those relationships, you can use @`MR`@ (short for @Maybe Relationships@), the relational equivalent of @'M'@.

-- $exclusive
-- A relationship can be made exclusive by setting the following Bool on the Component instance:
--
-- @
-- instance 'Component' FooRel where
--   'isExclusiveRel' = 'True'
-- @
--
-- This will make it so only one instance of a relationship can exist on an entity at once.
--
-- @
-- insert (Rel (FooRel, a)) c
-- insert (Rel (FooRel, b)) c
-- @
--
-- Will result in just @Rel (FooRel, b)@ being on @c@.

-- $hooks
-- There are a number of predefined hooks that are useful when working with relationships, which can be found in "Mischief.ECS.Hooks".
--
-- For instance, @relComplementary@ can be used to automate adding a complementary relationship on the target of a relationship.
--
-- As a quick example of why this is useful, let's create a @Before@/@After@ relationship between entities:
--
-- @
-- data Before = Before
-- data After = After
--
-- instance 'Component' Before where
--   'hooks' = 'relComplementary' ('const' After)
--
-- instance 'Component' After where
--   'hooks' = 'relComplementary' ('const' Before)
-- @
--
-- Now, when we do
--
-- @
-- 'insert' ('Rel' Before a) b
-- @
--
-- A @Rel After b@ will be inserted automatically on a.
--
-- And vice versa.
--
-- There are also @'relCleanupRemove'@ and @'relCleanupDespawn'@ for automatically removing a relationship (or ,respectively, despawning its entity) when its target has been despawned. And a
-- more generic @'relCleanup'@ which allows adding custom cleanup behavior.

-- The 'WithR' query filter lets us easily query for components of entities that have a certain relationship with a certain entity.
--
-- Getting a list of all entities that like bob.
--
-- @
-- x <- 'query'' 'E' ('WithR' @Likes bob)
-- @
--
-- Getting a list of all entities that like anyone.
--
-- @
-- x <- 'query'' 'E' ('WithR' @Likes Any)
-- @
--
-- We can also modify @Likes@ to have an @Int@ as well, representing how much an entity likes another:
--
-- @
-- data Likes = Likes 'Int' deriving ('Component')
-- @
--
-- @
-- 'insert' ('Rel' (Likes 5, alice), 'Rel' (Likes 8, charlie)) bob
-- @
--
-- The 'R' marker type can be used in a query to get a @['Result' ('Rel' c)]@ for each entity.
--
-- Getting the name and all the Likes relationships of all entities.
--
-- @
-- x <- query (C \@Name, 'R' \@Likes Any)
-- @
--
-- @
-- x :: [('Result' Name, ['Result' ('Rel' Likes)])]
-- @
--
--
-- Getting the name and the Like relationship with bob for all entities.
--
-- @
-- x <- query (C \@Name, 'R' \@Likes bob)
-- @
--
-- @
-- x :: [('Result' Name, 'Result' ('Rel' Likes))]
-- @
--
-- Note that @'R' \@Likes@ will limit the query to only the archetypes that contain any relation with @Likes@.
-- You can also use @'MR'@ (Maybe relationship) to also include the entities that don't contain such relationships.
--
-- A component can be made @exclusive@ by setting the following 'Bool' in the 'Component' instance:
--
-- @
-- instance 'Component' Likes where
--   'isExclusiveRel' = 'True'
-- @
--
-- If a component is exclusive, there can only be one relationship containing it on an entity at once.
--
-- For instance, if we do:
--
-- @
-- 'insert' ('Rel' (Likes, alice) bob
-- 'insert' ('Rel' (Likes, charlie)) bob
-- @
--
-- @(Likes, charlie)@ will overwrite @(Likes, alice)@.
--
-- This is useful for relationships such as 'ChildOf', since an entity can only have one parent at a time.
