{-# OPTIONS_GHC -Wno-unused-imports #-}

-- |
-- Module: Components Tutorial
-- Description: Introductory Tutorial
--
-- This module walks the user through setting up Mischief and creating a simple app.
--
-- [Next Chapter: Coding a Dungeon Game]("Mischief.ECS.Tutorial.Dungeon")
--
-- [Main Page]("Mischief.ECS")
module Mischief.ECS.Tutorial.Startup
  ( -- * Learn You an ECS for Great Mischief! - 1. Startup Guide

    -- * What do I need to know?
    -- $know

    -- * Setup
    -- $setup

    -- * Text
    -- $text

    -- * The App
    -- $app

    -- * The ECS
    -- $ecs

    -- * Your First System
    -- $firstSystem

    -- * Your First Component
    -- $firstComp

    -- * Your First Query
    -- $firstQuery

    -- * Your First Mutation
    -- $firstMut

    -- * Your First Resource
    -- $res

    -- * Your First Relationship
    -- $rel

    -- * Your First Transitive Query
    -- $trans

    -- * Extra: From
    -- $from

    -- * What's Next?
    -- $next

    -- * [Next Chapter: Coding a Dungeon Game]("Mischief.ECS.Tutorial.Dungeon")
  )
where

import Control.Monad (when)
import Data.Foldable (for_)
import Data.Traversable (for)
import Mischief.ECS

-- $know
-- This book doesn't assume any knowledge of other game engines or programming paradigms, but it does expect some Haskell knowledge.
--
-- While it is possible to read this book and get a pretty good idea of what Mischief is and how it works, you'll have a much better time
-- if you have at least a very basic understanding of Haskell syntax.

-- $setup
-- In order to use Mischief, you'll first need to install @GHC@ and @cabal@. You can follow [this](https://www.haskell.org/cabal/) quick-start guide in order to do that.
--
-- After you have a new project set up, just add @mischief-ecs@ under @build-depends@ in you @.cabal@ file.
--
-- We recommend using @GHC2024@ as the language standard (set in your @.cabal@ file).
--
-- == Language Extensions
-- We generally recommend using the following language extensions in a Mischief project:
--
-- @
-- DeriveAnyClass
-- DuplicateRecordFields
-- NoFieldSelectors
-- DerivingStrategies
-- OverloadedRecordDot
-- MultiWayIf
-- OverloadedStrings
-- QuasiQuotes
-- RequiredTypeArguments
-- TypeFamilyDependencies
-- @
--
-- @QuasiQuotes@ and @OverloadedStrings@ are especially important because some Mischief features are not available without them (namely quasi-queries and logging).
-- The rest of the extensions are highly optional.
-- You can paste these extensions in the @default-extensions@ field of your @.cabal@ file.

-- $text
--
-- Mischief uses @Text@ instead of @String@ where possible, including in its logging system.
-- The 'i' macro from @string-interpolate@ is re-exported by Mischief and will be often used for logging in this tutorial.
--
-- Sometimes functions from @Data.Text@ are used as well (such as @T.show@), so it's recommended to add @text@ as a dependency to your project and to qualify it when you want to use it:
--
-- @
-- import "Data.Text" qualified as T
-- @

-- $app
-- A Mischief program usually starts with creating an app and adding a plugin to it.
--
-- @
-- import "Mischief.ECS.Prelude"
--
-- main :: 'IO' ()
-- main = do
--   app <- 'newApp'
--   'addPlugin' \@MyPlugin app
--   'runApp' app
--
-- data MyPlugin
--
-- instance 'Plugin' MyPlugin
-- @
--
-- If you copy this code into your project and run it using @cabal run@, your app will start! Although we haven't told it to do anything yet.
--
-- The @App@ is a wrapper around our @World@, which is the structure containing all data stored by the ECS. It allows us to add
-- initializition instructions and to plug additional logic into our game through @Plugins@.

-- $ecs
-- Mischief's ECS logic is designed to be very approachat@ble and simple to write.
--
-- @Components@ are just types deriving the @Componen typeclass.
--
-- @
-- data Position = Position {x :: 'Float', y :: 'Float'} deriving ('Component')
-- @
--
-- @Systems@ are functions in the @System@ monad.
--
-- @
-- printPositions :: 'System' ()
-- printPositions = do
--   'info' . T.'Data.Text.show' =<< ['q'|Position|]
-- @
--
-- @Entities@ are ids used to represent and manipulate data.
--
-- @
-- data Entity = Entity 'Int'
-- @

-- $firstSystem
-- Paste the following function into your module:
--
-- @
-- helloWorld :: 'System' ()
-- helloWorld = 'info' "Hello World!"
-- @
--
-- This will be our first system. The only remaining step is to schedule it to run!
--
-- @
-- instance 'Plugin' MyPlugin where
--   'Mischief.ECS.App.Plugins.init' :: 'System' ()
--   'Mischief.ECS.App.Plugins.init' = do
--      'systems' helloWorld
--        & 'schedule' Update
-- @
--
-- The @systems@ function will grab the system for us, and @schedule Update@ will add it to the Update schedule,
-- making it run once per frame. If you run your app again, you will see \"Hello World!\" printed to your terminal many, many times.
--
-- As you may have noticed, the @init@ we give to the Plugin is, in itself, a system! There's nothing differentiating
-- the logic you write here from the logic ran at any point in your app's runtime. @init@ is just a convenient way of
-- adding some initialization that happens before anything else, but we'll get into that later.

-- $firstComp
-- Let's do a little more than greeting the whole world, let's greet some individual people!
--
-- In ECS, you would generally model people as entities with a set of components that define them. Let's start with a simple @Person@ component:
--
-- @
-- data Person = Person deriving ('Component')
-- @
--
-- So how can we give people names? In a more traditional design you could just add a @name :: String@ field to @Person@. But the ECS makes you think of it differently!
-- A @Name@ is just a piece of data that can be attached to anything. A dog could also have a name. So why not just make a @Name@ component?
--
-- @
-- data Name = Name 'String' deriving ('Component')
-- @
--
-- No need to define it though, since this exact @Name@ is already defined internally by Mischief and exported by the Prelude.
--
-- Now that we can represent people with names, let's make a system that spawns some:
--
-- @
-- addPeople :: 'System' ()
-- addPeople = do
--   kim <- 'spawn' (Person, Name \"Kimberly\")
--   nick <- 'spawn' (Person, Name \"Nicholas\")
--   flo <- 'spawn' (Person, Name \"Florian\")
--   'pure' ()
-- @
--
-- You can register it to run on the app's Startup schedule, making it run only once, at the start:
--
-- @
-- 'Mischief.ECS.App.Plugins.init' _ = do
--    'systems' helloWorld
--      & 'schedule' Update
--
--    'systems' addPeople
--      & 'schedule' Startup
-- @

-- $firstQuery
-- If you run your app, the people will be spawned but we aren't doing anything with them yet! Let's make a system that greets them:
--
-- @
-- greetPeople :: 'System' ()
-- greetPeople = do
--   people <- 'query' ('mkQuery' ('C' \@Name, 'C' \@Person))
--   'for_' people $ \\(name, _) -> do
--     'info' ['i'|Hello #{name}!|]
-- @
--
-- The above @query@ function will grab the @Name@ and @Person@ of every entity. We then iterate over them in order to greet them.
--
-- The @Person@ component however, is only queried to ensure we are querying the right entities. We don't care about its value at all! So we can instead write it
-- as a filter to limit the types of entities selected by the query and save us the trouble of carrying an extra variable around.
--
-- @
-- greetPeople :: 'System' ()
-- greetPeople = do
--   people <- 'query' ('mkQuery'' ('C' \@Name) ('With' ('C' \@Person)))
--   'for_' people $ \\name ->
--     'info' ['i'|Hello #{name}!|]
-- @
--
-- @(With (C \@Person))@ is a filter, telling our query builder to only select entities with the @Person@ component. @mkQuery'@ is a
-- variant of @mkQuery@ that also takes a filter.
--
-- Mischief has two equivalent ways of writing queries. The normal way that you've seen above, and the quasi way:
--
-- @
-- people <- 'query' ['q'|Name / With Person|]
-- @
--
-- Quasi-queries are macros meant to simplify writing queries. They'll become especially helpful once we start dealing
-- with relationships and transitive queries.
--
-- Additionally, Mischief lets you write and process queries by piping dedicated functions into each other. For instance, our earlier function is equivalent to:
--
-- @
-- greetPeople :: 'System' ()
-- greetPeople = do
--   ['q'|Name / With Person|]
--     & 'qinfo' (\\name -> ['i'|Hello #{name}!|])
--     & 'query_'
-- @
--
-- The quasi-query (@[q|..|]@) produces our query, we then use @qinfo@ to display a message to the terminal for each element in the query,
-- and finally we use @query_@ to run all the commands and discard the results (@query@ returns the results).
--
-- Now we can schedule this system to also run:
--
-- @
-- 'Mischief.ECS.App.Plugins.init' = do
--    'systems' (helloWorld, greetPeople)
--      & 'schedule' Update
--
--    'systems' addPeople
--      & 'schedule' Startup
-- @
--
-- Running our app will result in the following output:
--
-- @
-- [INFO] Hello World!
-- [INFO] Hello Kimberly!
-- [INFO] Hello Nicholas!
-- [INFO] Hello Florian!
-- @
--
-- Note that \"Hello World\" might show above or beneath the others. That's because systems in the same schedule can run in any order unless they are explicitly ordered.

-- $firstMut
-- If we want to change the name of some people, we can apply a mutation to a value obtained from the query:
--
-- @
-- updateFlo :: 'System' ()
-- updateFlo = do
--   people <- 'query' ['q'|E, Name / With Person|]
--   'for_' people $ \\(entity, name) -> do
--     'when' (name == Name \"Florian\") $
--       'insert' (Name \"Florianne\") entity
-- @
--
-- We are querying the name of each entity (@Name@), along with its actual id (@E@). We then iterate over all the names, and once we see \"Florian\", we
-- re-insert the component, changing its value to \"Florianne\".
--
-- Although.. that feels awfully imperative doesn't it? We can also write the same system as:
--
-- @
-- updateFlo :: 'System' ()
-- updateFlo = do
--   ['q'|Name / With Person|]
--     & 'qfilter' (== Name \"Florian\")
--     & 'qinsert' (\\_ -> Name \"Florianne\")
--     & 'query_'
-- @
--
-- This time we apply a filter over our Query, leaving only those entities with their name set to \"Florian\". We then use @qinsert@ to
-- map the old name to the new one and insert it on the entity.
--
-- Let's add the new system to a schedule:
--
-- @
-- 'Mischief.ECS.App.Plugins.init' = do
--    'systems' (helloWorld, greetPeople)
--      & 'schedule' Update
--
--    'systems' addPeople
--      & 'schedule' Startup
--
--    'systems' updateFlo
--      & 'before' greetPeople
--      & 'schedule' Update
-- @
--
-- Note that we have explicitly ordered @updateFlo@ to happen /before/ @greetPeople@. We want to only greet Flo after their name has changed!

-- $res
-- Resources are a great way to store global information that can be easily written to and read in any system.
--
-- Let's say we want to have a custom greeting that we can change at runtime. We could store that in a resource:
--
-- @
-- data Greeting = Greeting 'String' deriving ('Component')
-- @
--
-- We'll also give it a @Show@ instance to make printing it easier:
--
-- @
-- instance 'Show' Greeting where
--   'show' (Greeting a) = a
-- @
--
-- Yes, resources are just normal components! Any component can be stored and retrieved as a resource by using @insertRes@ and @res@.
--
-- Let's insert a greeting from our init system:
--
-- @
-- 'Mischief.ECS.App.Plugins.init' = do
--    'systems' (helloWorld, greetPeople)
--      & 'schedule' Update
--
--    'systems' addPeople
--      & 'schedule' Startup
--
--    'systems' updateFlo
--      & 'before' greetPeople
--      & 'schedule' Update
--
--   'insertRes' (Greeting \"Hey\")
-- @
--
-- And let's modify @greetPeople@ so that it uses the current greeting from the resource:
--
-- @
-- greetPeople :: 'System' ()
-- greetPeople = do
--   'Just' greeting <- 'res' \@Greeting
--
--   ['q'|Name / With Person|]
--     & 'qinfo' (\\name -> ['i'|#{greeting} #{name}!|])
--     & 'query_'
-- @
--
-- We are using @res@ to ask the world for the resource, which may or may not exist at that time. In our case it will always exist, because the plugin's @init@ runs before
-- any scheduled system, so it is safe to assume the result will be a @Just@. But what if we don't want to take that risk?
--
-- @
-- greetPeople :: 'System' ()
-- greetPeople = do
--   ['q'|Name, Res Greeting / With Person|]
--     & 'qinfo' (\\(name, greeting) -\> ['i'|#{greeting} #{name}!|])
--     & 'query_'
-- @
--
-- We have now included the resource itself in our query. This will make the query simply return no elements if the resource doesn't exist,
-- saving us the trouble of having to treat that case.
--
-- You should now see this when running the app:
--
-- @
-- [INFO] Hello World!
-- [INFO] Hey Kimberly!
-- [INFO] Hey Nicholas!
-- [INFO] Hey Florianne!
-- @

-- $rel
-- Relationships in Mischief are pairs made up of a Component and an Entity. Let's implement a simple relationship between our entities that says which like which.
--
-- We'll start by defining a component:
--
-- @
-- data Likes = Likes deriving ('Component')
-- @
--
-- Let's now modify our spawning system to also insert relationships between our three entities. We can insert a relationship using the @Rel@ keyword.
--
-- @
-- addPeople :: 'System' ()
-- addPeople = do
--   kim <- 'spawn' (Person, Name \"Kimberly\")
--   nick <- 'spawn' (Person, Name \"Nicholas\")
--   flo <- 'spawn' (Person, Name \"Florian\")
--
--   'insert' ('Rel' Likes kim) flo
--   'insert' ('Rel' Likes nick, 'Rel' Likes flo) kim
-- @
--
-- We've now made @flo@ like @kim@, and we've made @kim@ like both @nick@ and @flo@!.

-- $trans
-- We now have relationships but we aren't doing much with them. What about having a system that displays the name of each entity, along with the name of all entities they like?
--
-- As an intermediary step, let's not display the names, but just the id's of the entities:
--
-- @
-- showLikes :: 'System' ()
-- showLikes = do
--   people <- 'query' $ 'mkQuery' ('C' \@Name, 'R' \@Likes Any)
--
--   'for_' people $ \\(name, likes) -> do
--     info [i|#{name} likes #{'map' (.target) likes}|]
-- @
--
-- We are are querying the @Name@ as well as /Any/ @Likes@ relationships that an entity has. The @R \@Likes Any@ will return a @[Rel Likes]@.
-- Each @Rel@ has two fields: @.target@ and @.comp@, one for the target entity, and one for the actual data of the relationship.
--
-- As shown above, we can just map each @Rel Likes@ in the list to its @.target@, and display those. If we want to also grab the name of each of those entities,
-- we can use the @get@ function. It's the same as @query@, but it runs our queries for a single given Entity. So we can put this inside the @for_@ to get the names:
--
-- @
-- names \<- 'for' likes $ \\'Rel'{target} -\> 'get' target ['q'|Name|]
-- @
--
-- But.. that's already very convoluted. Luckily, the queries give us a few ways out of this:
--
-- First, we have the @outgoing@ traversal:
--
-- @
-- import "Mischief.ECS.Relationships.Graph" qualified as Graph
-- @
--
-- @
-- showLikes :: 'System' ()
-- showLikes = do
--   ['q'|Name|]
--     & 'qrelateMany' (Graph.[outgoing]('Mischief.ECS.Relationships.Graph') \@Likes) ['q'|Name|]
--     & 'qjoin' (,)
--     & 'qinfo' (\\(name, likes) -\> [i|#{name} likes #{likes}|])
--     & 'query_'
-- @
--
-- @qrelateMany@ expects an @Entity -> m (Maybe Entity)@ function (which is exactly what @Graph.outgoing@ gives us) and another query.
-- It will return a @Join@ between our two queries, matching each element from the main query with a set of elements from the second query (the name
-- of each entity, with the names of the entities it likes).
--
-- Then we use @qjoin@ to apply the join, specifying  how the elements of the two queries should be merged. In this case we just pair them together using @(,)@.
--
-- And second, there is a mechanism we can make use of called a @transitive query@, which looks like this:
--
-- @
-- showLikes :: 'System' ()
-- showLikes = do
--   'mkQuery' ('C' \@Name, 'R' \@Likes ('Q' ('C' \@Name)))
--     & 'qinfo' (\\(name, likes) -\> [i|#{name} likes #{likes}|])
--     & 'query_'
-- @
--
-- Or, in quasi-notation:
--
-- @
-- showLikes :: 'System' ()
-- showLikes = do
--   ['q'|Name, Likes -\> (Name)|]
--     & 'qinfo' (\\(name, likes) -\> [i|#{name} likes #{likes}|])
--     & 'query_'
-- @
--
-- Pretty nice, huh?
--
-- The transitive query grabs the specified components from the targets of our relationship, doing exactly what @qrelateMany@ does.
--
-- Now let's schedule our new system to run:
--
-- @
-- 'Mischief.ECS.App.Plugins.init' = do
--    'systems' (helloWorld, greetPeople, showLikes)
--      & 'schedule' Update
--
--    'systems' addPeople
--      & 'schedule' Startup
--
--    'systems' updateFlo
--      & 'before' (greetPeople, showLikes)
--      & 'schedule' Update
--
--   'insertRes' (Greeting \"Hey\")
-- @
--
-- We should now see these additional lines printed to the terminal:
--
-- @
-- [INFO] Florianne likes [From (42v1, Kimberly)]
-- [INFO] Kimberly likes [From (44v1, Nicholas),From (45v1, Florianne)]
-- @

-- $from
-- You may have noticed earlier, when we query for @-> (Name)@ and then print the names, we don't get the actual names, but instead
-- something that looks like @From (42v1, Kimberly)@.
--
-- That's because, when doing transitive queries (either by @-> (..)@ or through functions such as @qrelateMany@), the components come wrapped in this:
--
-- @
-- data From c = From {comp :: c, entity :: Entity}
-- @
--
-- They have a different origin entity than the other components in our query, and this is our main way of keeping track of that.
--
-- One cool utility that comes of this is that we can very easily change the values of foreign components by just mapping them to a different value. For instance,
-- this next query gets all the children of an entity and sets their names to be the same as the main entity:
--
-- @
-- ['q'|Name|]
--   & 'qrelateMany' (Graph.'Mischief.ECS.Relationships.Graph.incoming' \@ChildOf) ['q'|Name|]
--   & 'qjoin' (,)
--   & 'qinsert' (\\(parentName, childNames) -> 'map' (\\(From child _) -> From child parentName) childNames)
--   & 'query_'
-- @

-- $next
-- What you learn next is up to you.
--
-- The next chapter will have you working on a little dungeon game in the terminal and introduce you to more notions. If you prefer to learn by example it's recommended to
-- go check that out.
--
-- After that, the next chapters go into detail on various topics (Components, Queries, Systems, etc.), so you may choose to just read those directly, and maybe come
-- back to the game later.
